apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-service
spec:
  selector:
    app: cloud-native-app
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000
  type: LoadBalancer
  externalIPs:
  - 45.64.104.244